Repository msdio/Tamago, pull requests merged in 2023-04, with the labels that each got.

#250 긴글 목록 조회시 전체페이지 목록개수도 return
  backend/src/main/java/com/project/Tamago/controller/TypingController.java
  backend/src/main/java/com/project/Tamago/dto/LongTypingDto.java
  backend/src/main/java/com/project/Tamago/dto/mapper/DataMapper.java
  backend/src/main/java/com/project/Tamago/dto/responseDto/LongTypingResDto.java
  backend/src/main/java/com/project/Tamago/service/LongTypingService.java
  backend/src/test/java/com/project/Tamago/service/LongTypingServiceTest.java
Labels: 💻 Backend, ♻️ 리팩토링

#240 연습모드 결과 모달 수정
  .vscode/settings.json
  client/src/apis/typing.ts
  client/src/components/common/PrepareAlert/index.tsx
  client/src/components/common/ResultModal/InfoList/index.tsx
  client/src/components/common/ResultModal/exam-mode.tsx
  client/src/components/common/ResultModal/practice-mode.tsx
  client/src/components/common/ResultModal/types.ts
  client/src/components/practice/short/_hook/contextShortTyping.tsx
  client/src/types/typing.ts
  client/src/utils/time.ts
Labels: 🛩 기능 추가, 💻 Frontend

#243 [#242] 긴 글 연습 타이핑 종료시 api 요청 및 모달창 출력
  client/src/apis/auth.ts
  client/src/apis/typing.ts
  client/src/atom/userProfile.ts
  client/src/components/common/ResultModal/practice-mode.tsx
  client/src/components/header/index.tsx
  client/src/components/practice/long/Typing/index.tsx
  client/src/hooks/useUserProfile.ts
  client/src/pages/index.tsx
Labels: 🛩 기능 추가, 💻 Frontend

#246 [#241] 폰트 디자인 시스템
  client/src/styles/theme.ts
  client/src/styles/typo.ts
Labels: 🌈 프로젝트 세팅, 💻 Frontend

#248 [#245] 긴 글 리스트 페이지네이션 구현
  client/src/apis/typing.ts
  client/src/components/common/ResultModal/practice-mode.tsx
  client/src/components/practice/long/Content/index.tsx
  client/src/components/practice/long/List/TypingListPagination/index.stories.tsx
  client/src/components/practice/long/List/TypingListPagination/index.tsx
  client/src/components/practice/long/List/index.tsx
  client/src/components/practice/long/Typing/index.tsx
  client/src/components/practice/long/TypingDetailPagination/index.stories.tsx
  client/src/components/practice/long/TypingDetailPagination/index.tsx
  client/src/constants/typing.ts
  client/src/icons/Search.tsx
  client/src/pages/practice/long/index.tsx
Labels: 🛩 기능 추가, 💻 Frontend, 🎨 UI

#251 메인 화면에 수민님 변경사항 반영
  client/src/components/home/Banner/index.tsx
  client/src/components/home/Landing/index.tsx
  client/src/components/home/Menus/index.tsx
Labels: 💻 Frontend, 🎨 UI

#247 글 선택 페이지 구현
  .vscode/settings.json
  client/public/images/speech-bubble.png
  client/src/components/choice/CheckedLayout.tsx
  client/src/components/choice/Heading.tsx
  client/src/components/choice/LanguageBox/ProgrammingDropDown.tsx
  client/src/components/choice/LanguageBox/ProgrammingDropDownItem.tsx
  client/src/components/choice/LanguageBox/TextBox.tsx
  client/src/components/choice/LanguageBox/index.tsx
  client/src/components/choice/index.tsx
  client/src/components/header/DropDown/Item.tsx
  client/src/components/header/DropDown/index.tsx
  client/src/components/practice/long/Typing/TypingHeader/index.tsx
  client/src/components/practice/short/InfoBar/ModeList.tsx
  client/src/constants/animations.ts
  client/src/constants/language.ts
  client/src/constants/paths.ts
  client/src/constants/typing.ts
  client/src/icons/Arrow.tsx
  client/src/icons/DownArrow.tsx
  client/src/icons/SmallArrow.tsx
  client/src/icons/types.ts
  client/src/pages/practice/short/choice.tsx
  client/src/pages/practice/short/index.tsx
  client/src/types/language.ts
  client/src/types/typing.ts
  client/src/utils/language.ts
Labels: 💻 Frontend, 🎨 UI

#249 [#227] 글 선택 페이지와 짧은 글 연습모드 연결
  client/src/apis/typing.ts
  client/src/constants/typing.ts
  client/src/pages/practice/short/index.tsx
Labels: 💻 Frontend, ♻️ 리팩토링

#256 통계 컴포넌트 스타일을 완성했습니다.
  client/package.json
  client/src/components/charts/AreaChart/index.stories.tsx
  client/src/components/charts/AreaChart/index.tsx
  client/src/components/charts/BarChart/index.tsx
  client/src/components/charts/LineChart/index.stories.tsx
  client/src/components/charts/LineChart/index.tsx
  client/src/utils/sort.ts
  client/src/utils/test/sort.test.ts
  client/src/utils/test/tier.test.ts
  client/src/utils/tier.ts
  client/yarn.lock
Labels: 🛩 기능 추가, 💻 Frontend, 🧪 테스트

#253 1200px 미만인 경우 서비스 사용 불가능하도록 처리
  client/src/components/common/Hider/index.tsx
  client/src/pages/_app.tsx
Labels: 🛩 기능 추가, 💻 Frontend, 🎨 UI

#252 로그인 후 유저정보가 노출되도록 변경
  client/src/apis/auth.ts
  client/src/atoms/userProfile.ts
  client/src/components/header/index.tsx
  client/src/components/login/LoginForm/index.tsx
  client/src/components/login/index.tsx
  client/src/components/typing/long/Typing/index.tsx
  client/src/hooks/useUserProfile.ts
  client/src/utils/test/char.test.ts
Labels: 🛩 기능 추가, 💻 Frontend, 🔨 버그 해결

#264 vscode의 typescript 버전 업그레이드로 인한 ts server 에러 수정
  .vscode/settings.json
Labels: 🔨 버그 해결

#257 [#158] 에러로그를 slack으로 전송하는 모니터링 구현
  backend/build.gradle
  backend/src/main/java/com/project/Tamago/TamagoApplication.java
  backend/src/main/java/com/project/Tamago/common/Constant.java
  backend/src/main/java/com/project/Tamago/common/annotation/SlackAlarm.java
  backend/src/main/java/com/project/Tamago/common/enums/AlarmLevel.java
  backend/src/main/java/com/project/Tamago/common/exception/exceptionHandler/ControllerAdvice.java
  backend/src/main/java/com/project/Tamago/common/logger/RequestStorage.java
  backend/src/main/java/com/project/Tamago/common/logger/SlackAppender.java
  backend/src/main/java/com/project/Tamago/common/logger/SlackMessageGenerator.java
  backend/src/main/java/com/project/Tamago/common/logger/TamagoSlack.java
  backend/src/main/java/com/project/Tamago/common/response/CustomResponse.java
  backend/src/main/java/com/project/Tamago/configuration/config/CorsConfig.java
  backend/src/main/java/com/project/Tamago/configuration/config/RedisConfig.java
  backend/src/main/java/com/project/Tamago/configuration/config/SecurityConfig.java
  backend/src/main/java/com/project/Tamago/configuration/config/SwaggerConfig.java
  backend/src/main/java/com/project/Tamago/configuration/config/WebConfig.java
  backend/src/main/java/com/project/Tamago/configuration/resolver/LoginArgumentResolver.java
  backend/src/main/java/com/project/Tamago/controller/AuthController.java
  backend/src/main/java/com/project/Tamago/controller/StatisticController.java
  backend/src/main/java/com/project/Tamago/controller/TypingController.java
  backend/src/main/java/com/project/Tamago/controller/TypingHistoryController.java
  backend/src/main/java/com/project/Tamago/controller/UserController.java
  backend/src/main/java/com/project/Tamago/security/jwt/JwtAuthorizationFilter.java
  backend/src/main/java/com/project/Tamago/security/jwt/handler/CustomAccessDeniedHandler.java
  backend/src/main/java/com/project/Tamago/security/jwt/handler/CustomAuthenticationEntryPointHandler.java
Labels: 🛩 기능 추가, 💻 Backend

#271 클라이언트의 ip를 제대로 반환하지못하는 에러
  backend/src/main/java/com/project/Tamago/common/logger/SlackMessageGenerator.java
Labels: 💻 Backend, 🔨 버그 해결

#263 짧은글, 글 선택 화면 버그 픽스
  .vscode/settings.json
  client/public/images/writing-type/bottom-grass.png
  client/public/images/writing-type/eggs.png
  client/public/images/writing-type/speech-bubble.png
  client/src/components/choice/CheckedLayout.tsx
  client/src/components/choice/LanguageBox/ProgrammingDropDown.tsx
  client/src/components/choice/LanguageBox/index.tsx
  client/src/components/choice/index.tsx
  client/src/components/common/CheckedLayout/index.tsx
  client/src/components/typing/short/InfoBar/ModeLabel.tsx
  client/src/components/typing/short/InfoBar/ModeList.tsx
  client/src/components/typing/short/InfoBar/index.tsx
  client/src/components/typing/short/_hook/useCurrentTyping.ts
  client/src/constants/animations.ts
  client/src/constants/language.ts
  client/src/constants/typing.ts
  client/src/types/language.ts
  client/src/types/typing.ts
  client/src/utils/language.ts
Labels: 💻 Frontend, 🔨 버그 해결

#265 연습모드 결과창 parmeter 변경
  client/src/components/common/ResultModal/practice-mode.tsx
  client/src/components/typing/long/Typing/index.tsx
  client/src/components/typing/short/_hook/contextShortTyping.tsx
Labels: 💻 Frontend, 🔨 버그 해결

#272 긴글 등록시 페이지를 제대로 분리못하는 에러 fix
  backend/src/main/java/com/project/Tamago/dto/mapper/DataMapper.java
Labels: 💻 Backend, 🔨 버그 해결

#267 [#260] 로그인, 회원가입 화면에서의 에러들 수정
  client/src/components/login/Form/index.tsx
  client/src/components/password/index/index.tsx
  client/src/components/signup/Form/index.tsx
  client/src/hooks/useToggle.ts
Labels: 💻 Frontend, 🔨 버그 해결

#268 [#260] 메인 화면 버그들 수정
  client/src/components/header/DropDown/Item.tsx
  client/src/components/header/DropDown/index.tsx
  client/src/components/home/Menus/index.tsx
Labels: 💻 Frontend, 🔨 버그 해결

#274 긴 글 등록 기능 추가
  client/src/apis/typing.ts
  client/src/components/header/DropDown/index.tsx
  client/src/components/home/Menus/index.tsx
  client/src/components/register/Layout/index.tsx
  client/src/components/register/Long/index.tsx
  client/src/pages/register.tsx
Labels: 🛩 기능 추가, 💻 Frontend

#275 긴 글 리스트 페이지네이션 버그 해결 + 긴 글 리스트 타입 추가
  client/src/constants/typing.ts
  client/src/pages/practice/long/index.tsx
Labels: 💻 Frontend, 🔨 버그 해결, 🎨 UI

#285 페널티 감점 구현
  backend/src/main/java/com/project/Tamago/common/enums/Level.java
  backend/src/main/java/com/project/Tamago/common/enums/ResponseCode.java
  backend/src/main/java/com/project/Tamago/controller/TypingExamController.java
  backend/src/main/java/com/project/Tamago/domain/Tier.java
  backend/src/main/java/com/project/Tamago/service/TypingExamService.java
  backend/src/test/java/com/project/Tamago/service/TypingExamServiceTest.java
Labels: 🛩 기능 추가, 💻 Backend, ♻️ 리팩토링

#284 글 선택 화면 모달 가려지는 문제 수정
  client/src/components/choice/LanguageBox/ProgrammingDropDown.tsx
Labels: 💻 Frontend, 🔨 버그 해결, 🎨 UI

#282 [#260] 메인화면 stat 버튼 클릭 시 alert, outline 색상 오류 수정
  client/src/components/home/Stats/index.tsx
  client/src/pages/404.tsx
Labels: 💻 Frontend, 🔨 버그 해결

#280 실전모드 결과창 애니매이션 추가
  client/public/images/egg.png
  client/src/apis/typing.ts
  client/src/components/choice/LanguageBox/ProgrammingDropDown.tsx
  client/src/components/common/ResultModal/InfoList/Item.tsx
  client/src/components/common/ResultModal/exam-mode/ScoreInfo.tsx
  client/src/components/common/ResultModal/exam-mode/index.tsx
  client/src/components/typing/short/_hook/contextShortTyping.tsx
  client/src/constants/animations.ts
Labels: 💻 Frontend, 🎨 UI

#277 실전모드 결과 모달 구현
  client/public/images/egg.png
  client/src/apis/typing.ts
  client/src/components/choice/LanguageBox/ProgrammingDropDown.tsx
  client/src/components/common/ResultModal/InfoList/Item.tsx
  client/src/components/common/ResultModal/InfoList/index.tsx
  client/src/components/common/ResultModal/exam-mode/ScoreInfo.tsx
  client/src/components/common/ResultModal/exam-mode/index.tsx
  client/src/components/home/Tiers/index.tsx
  client/src/components/typing/short/InfoBar/ModeLabel.tsx
  client/src/components/typing/short/InfoBar/index.tsx
  client/src/components/typing/short/_hook/contextShortTyping.tsx
  client/src/constants/animations.ts
  client/src/constants/tierInfo.ts
  client/src/styles/modal.ts
  client/src/types/tier.ts
  client/src/utils/tier.ts
Labels: 💻 Frontend, 🎨 UI

#281 [#254] 긴 글 실전 모드 라우팅 및 api 연결
  client/src/apis/typing.ts
  client/src/components/common/ResultModal/practice-mode.tsx
  client/src/components/header/DropDown/index.tsx
  client/src/components/header/index.tsx
  client/src/components/home/Menus/index.tsx
  client/src/components/typing/long/Content/index.tsx
  client/src/components/typing/long/Exam/index.tsx
  client/src/components/typing/long/Layout/index.tsx
  client/src/components/typing/long/List/TypingListPagination/index.tsx
  client/src/components/typing/long/List/index.tsx
  client/src/components/typing/long/Practice/index.tsx
  client/src/components/typing/long/Typing/InfoBar/index.tsx
  client/src/components/typing/long/Typing/TypingHeader/index.tsx
  client/src/components/typing/long/TypingChar/index.tsx
  client/src/components/typing/long/TypingExit/index.stories.tsx
  client/src/components/typing/long/TypingExit/index.tsx
  client/src/components/typing/long/TypingHeader/InfoBar/InfoBarItem.tsx
  client/src/components/typing/long/TypingHeader/InfoBar/index.tsx
  client/src/components/typing/long/TypingHeader/index.stories.tsx
  client/src/components/typing/long/TypingHeader/index.tsx
  client/src/components/typing/long/TypingLine/index.tsx
  client/src/components/typing/short/InfoBar/index.tsx
  client/src/components/typing/short/_hook/useActualShortTyping.tsx
  client/src/constants/language.ts
  client/src/constants/paths.ts
  client/src/constants/typing.ts
  client/src/hooks/useStopWatch.ts
  client/src/icons/Heart.tsx
  client/src/pages/actual/long/index.tsx
  client/src/pages/index.tsx
  client/src/pages/practice/index.tsx
  client/src/pages/practice/long/detail/index.tsx
  client/src/pages/practice/long/index.tsx
  client/src/types/typing.ts
Labels: 🛩 기능 추가, 💻 Frontend, 🎨 UI

#287 실전모드 결과창 수정
  client/src/apis/error.ts
  client/src/apis/index.ts
  client/src/apis/typing.ts
  client/src/components/choice/index.tsx
  client/src/components/common/ResultModal/exam-mode/ScoreInfo.tsx
  client/src/components/common/ResultModal/exam-mode/index.tsx
  client/src/components/typing/short/_hook/contextShortTyping.tsx
  client/src/components/typing/short/_hook/useActualShortTyping.tsx
  client/src/components/typing/short/_hook/useCurrentTyping.ts
  client/src/pages/actual/short/index.tsx
Labels: 💻 Frontend, 🔨 버그 해결, ♻️ 리팩토링

#290 fix: response code 값들 추가 및 기존 값들 변경
  client/src/components/login/index.tsx
  client/src/components/register/Long/index.tsx
  client/src/components/signup/Form/index.tsx
  client/src/constants/responseCode.ts
Labels: 💻 Frontend, 📝 문서 작업

#294 [#293] meta 정보들 추가
  client/public/icons/chick.ico
  client/src/components/meta-info/index.tsx
  client/src/pages/_document.tsx
Labels: 🌈 프로젝트 세팅, 💻 Frontend

#295 fix: component error on typing/long/Exam
  client/src/components/typing/long/Exam/index.tsx
Labels: 💻 Frontend, 🔨 버그 해결

#298 feat: add badge svg animation
  backend/src/main/java/com/project/Tamago/view/BadgeView.java
Labels: 🛩 기능 추가, 🎨 UI

#301 tab 키 입력시 indent
  client/src/components/common/Checkbox/index.stories.tsx
  client/src/components/common/Checkbox/index.tsx
  client/src/components/home/Banner/index.tsx
  client/src/components/home/Menus/index.tsx
  client/src/components/home/Stats/index.tsx
  client/src/components/login/Form/index.tsx
  client/src/components/signup/Terms/index.tsx
  client/src/components/typing/long/List/index.tsx
  client/src/components/typing/long/Practice/index.tsx
Labels: 🛩 기능 추가, 💻 Frontend

#302 카카오 소셜 로그인
  client/public/images/kakaotalk_btn.png
  client/src/apis/auth.ts
  client/src/components/login/Form/index.tsx
  client/src/components/signup/Form/index.tsx
  client/src/pages/kakao-redirect.tsx
Labels: 🛩 기능 추가, 💻 Frontend

#308 라우팅 관련 에러 수정
  client/src/apis/auth.ts
  client/src/components/header/DropDown/index.tsx
  client/src/components/login/Form/index.tsx
  client/src/constants/paths.ts
Labels: 💻 Frontend, 🔨 버그 해결

#314 비밀번호 유효성 검사 수정
  backend/src/main/java/com/project/Tamago/dto/requestDto/JoinReqDto.java
Labels: 💻 Backend, 🔨 버그 해결

#315 비밀번호 정규식 변경
  client/src/utils/regex.ts
Labels: 💻 Frontend, 🔨 버그 해결

#316 fix: 유효성 검증 정규식 변경에 따른 테스트
  backend/src/test/java/com/project/Tamago/controller/AuthControllerTest.java
Labels: 🔨 버그 해결

#303 조회수 로직구현
  backend/src/main/java/com/project/Tamago/common/Constant.java
  backend/src/main/java/com/project/Tamago/common/annotation/Ip.java
  backend/src/main/java/com/project/Tamago/configuration/config/RedisConfig.java
  backend/src/main/java/com/project/Tamago/configuration/config/WebConfig.java
  backend/src/main/java/com/project/Tamago/configuration/resolver/IpAddressResolver.java
  backend/src/main/java/com/project/Tamago/controller/TypingController.java
  backend/src/main/java/com/project/Tamago/domain/LongTyping.java
  backend/src/main/java/com/project/Tamago/service/LongTypingService.java
  backend/src/test/java/com/project/Tamago/service/LongTypingServiceTest.java
Labels: 🛩 기능 추가, 💻 Backend

#320 swagger 연결 디렉토리 명 변경
  backend/src/main/java/com/project/tamago/configuration/config/SwaggerConfig.java
Labels: 💻 Backend, 🔨 버그 해결, ♻️ 리팩토링

#322 바뀐 dockerfiler run
  backend/src/main/java/com/project/tamago/configuration/config/SwaggerConfig.java
Labels: 🔨 버그 해결
