Repository msdio/Tamago, pull requests merged in 2023-03, with the labels that each got.

#105 메인 페이지 퍼블리싱이 완료되었습니다.
  client/public/images/home/abc.png
  client/public/images/home/background.png
  client/public/images/home/banner-message.png
  client/public/images/home/feather.png
  client/public/images/home/ganada.png
  client/public/images/home/graph-bar.png
  client/public/images/home/graph-circle.png
  client/public/images/home/yellow-chick-shadow.png
  client/public/images/home/yellow-chick.png
  client/public/images/tiers/tier-five.png
  client/public/images/tiers/tier-four.png
  client/public/images/tiers/tier-one.png
  client/public/images/tiers/tier-three.png
  client/public/images/tiers/tier-two.png
  client/public/images/tiers/tier-zero.png
  client/src/components/common/Tier/index.tsx
  client/src/components/home/Banner/index.tsx
  client/src/components/home/Footer/index.tsx
  client/src/components/home/Landing/index.tsx
  client/src/components/home/Layout/index.tsx
  client/src/components/home/Menus/index.tsx
  client/src/components/home/Stats/index.tsx
  client/src/components/home/Tiers/index.tsx
  client/src/components/password/complete/index.tsx
  client/src/constants/animations.ts
  client/src/constants/tierInfo.ts
  client/src/hooks/useIntersectionObserver.ts
  client/src/icons/CheckCircle.tsx
  client/src/icons/RightArrow.tsx
  client/src/icons/RightArrowWithCircle.tsx
  client/src/icons/ScrollIndicator.tsx
  client/src/icons/TamagoLogo.tsx
  client/src/icons/TamagoLogoWhite.tsx
  client/src/pages/_app.tsx
  client/src/styles/font.css
  client/src/styles/styles.ts
  client/src/types/tier.ts
Labels: 💻 Frontend, 🎨 UI

#111 [#106] Short Typing API 구현
  backend/src/main/java/com/project/Tamago/config/SecurityConfig.java
  backend/src/main/java/com/project/Tamago/controller/TypingController.java
  backend/src/main/java/com/project/Tamago/domain/Typing.java
  backend/src/main/java/com/project/Tamago/dto/ShortTypingDto.java
  backend/src/main/java/com/project/Tamago/dto/mapper/TypingMapper.java
  backend/src/main/java/com/project/Tamago/dto/mapper/UserMapper.java
  backend/src/main/java/com/project/Tamago/dto/responseDto/ProfileResDto.java
  backend/src/main/java/com/project/Tamago/dto/responseDto/ShortTypingListResDto.java
  backend/src/main/java/com/project/Tamago/repository/TypingRepository.java
  backend/src/main/java/com/project/Tamago/service/ShortTypingSerivce.java
  backend/src/main/java/com/project/Tamago/service/ShortTypingService.java
  backend/src/test/java/com/project/Tamago/controller/TypingControllerTest.java
  backend/src/test/java/com/project/Tamago/service/ShortTypingServiceTest.java
  dockerfile/sample_data.sql
Labels: 🛩 기능 추가, 💻 Backend

#115 [Test] test code 오류 상황 변경
  backend/src/test/java/com/project/Tamago/service/ShortTypingServiceTest.java
Labels: 💻 Backend, 🔨 버그 해결

#121 [#116] short-typing 파라미터를 통한 짧은 글 가져오기 및 사용자 오류 처리 추가
  backend/src/main/java/com/project/Tamago/controller/TestController.java
  backend/src/main/java/com/project/Tamago/controller/TypingController.java
  backend/src/main/java/com/project/Tamago/exception/exceptionHandler/ControllerAdvice.java
  backend/src/main/java/com/project/Tamago/exception/exceptionHandler/ErrorCode.java
  backend/src/main/java/com/project/Tamago/repository/TypingRepository.java
  backend/src/main/java/com/project/Tamago/service/ShortTypingService.java
  backend/src/test/java/com/project/Tamago/TamagoApplicationTests.java
  backend/src/test/java/com/project/Tamago/controller/TypingControllerTest.java
  backend/src/test/java/com/project/Tamago/service/ShortTypingServiceTest.java
Labels: 🛩 기능 추가, 💻 Backend

#119 Feature/client/short typing&login fix
  client/src/apis/auth.ts
  client/src/apis/index.ts
  client/src/apis/typing.ts
  client/src/components/common/Alert/index.stories.tsx
  client/src/components/common/Alert/index.tsx
  client/src/components/header/index.tsx
  client/src/components/login/Form/index.stories.tsx
  client/src/components/login/LoginForm/index.stories.tsx
  client/src/components/login/index.tsx
  client/src/components/practice/short/CurrentTyping/index.tsx
  client/src/components/practice/short/InfoBar/InfoBarItem.tsx
  client/src/components/practice/short/InfoBar/index.tsx
  client/src/components/practice/short/PrevTyping/index.tsx
  client/src/components/practice/short/index.tsx
  client/src/components/practice/short/useStopWatch.ts
  client/src/constants/hangul.ts
  client/src/icons/DownArrow.tsx
  client/src/icons/TwoRightArrow.tsx
  client/src/pages/practice/short.tsx
  client/src/utils/checkErrorWord.ts
  client/src/utils/time.ts
Labels: 🛩 기능 추가, 💻 Frontend

#131 [#104] 긴글 테이블 생성 및 긴글 목록 조회 api
  backend/build.gradle
  backend/src/main/generated/com/project/Tamago/dto/mapper/DataMapperImpl.java
  backend/src/main/java/com/project/Tamago/TamagoApplication.java
  backend/src/main/java/com/project/Tamago/constants/enums/Language.java
  backend/src/main/java/com/project/Tamago/controller/TypingController.java
  backend/src/main/java/com/project/Tamago/domain/BaseTimeEntity.java
  backend/src/main/java/com/project/Tamago/domain/LongTyping.java
  backend/src/main/java/com/project/Tamago/dto/mapper/DataMapper.java
  backend/src/main/java/com/project/Tamago/dto/responseDto/LongTypingResDto.java
  backend/src/main/java/com/project/Tamago/repository/LongTypingRepository.java
  backend/src/main/java/com/project/Tamago/service/LongTypingService.java
  backend/src/test/java/com/project/Tamago/controller/TypingControllerTest.java
  backend/src/test/java/com/project/Tamago/service/LongTypingServiceTest.java
  etc/dataMaker/sample_long_typing._data.sql
Labels: 🛩 기능 추가, 💻 Backend

#124 [#108] 디자인 시스템 정리 (컬러)
  client/src/components/common/Checkbox/index.tsx
  client/src/components/common/FormOr/index.tsx
  client/src/components/common/RegexInput/index.tsx
  client/src/components/common/Tier/index.tsx
  client/src/components/footer/index.tsx
  client/src/components/header/index.tsx
  client/src/components/home/Banner/index.tsx
  client/src/components/home/Footer/index.tsx
  client/src/components/home/Landing/index.tsx
  client/src/components/home/Stats/index.tsx
  client/src/components/login/Form/index.tsx
  client/src/components/password/change/index.tsx
  client/src/components/password/index/index.tsx
  client/src/components/signup/Form/EmailInput.tsx
  client/src/components/signup/Form/index.tsx
  client/src/components/signup/Terms/index.tsx
  client/src/constants/tierInfo.ts
  client/src/pages/designSystem.tsx
  client/src/styles/Button.ts
  client/src/styles/Input.ts
  client/src/styles/colors.ts
  client/src/types/tier.ts
Labels: 💻 Frontend, 🎨 UI

#134 successMessage삭제 customResponse 적용
  backend/src/main/generated/com/project/Tamago/dto/mapper/DataMapperImpl.java
  backend/src/main/java/com/project/Tamago/controller/AuthController.java
  backend/src/main/java/com/project/Tamago/controller/UserController.java
  backend/src/main/java/com/project/Tamago/dto/CustomResponse.java
  backend/src/main/java/com/project/Tamago/dto/SuccessMessage.java
Labels: ♻️ 리팩토링

#133 fix: 스토리북 에러 수정
  client/src/components/signup/Form/index.stories.tsx
Labels: 💻 Frontend, 🔨 버그 해결, 🎈 배포

#138 fix: 백엔드 CI 변경
  .github/workflows/backend-ci.yml
Labels: 🔨 버그 해결, 🎈 배포

#135 [#136] 타이핑 이후 결과창 보내기
  backend/src/main/generated/com/project/Tamago/dto/mapper/DataMapperImpl.java
  backend/src/main/java/com/project/Tamago/config/SecurityConfig.java
  backend/src/main/java/com/project/Tamago/controller/TypingHistoryController.java
  backend/src/main/java/com/project/Tamago/domain/TypingHistory.java
  backend/src/main/java/com/project/Tamago/dto/mapper/DataMapper.java
  backend/src/main/java/com/project/Tamago/dto/requestDto/TypingHistoryReqDto.java
  backend/src/main/java/com/project/Tamago/exception/exceptionHandler/ControllerAdvice.java
  backend/src/main/java/com/project/Tamago/exception/exceptionHandler/ErrorCode.java
  backend/src/main/java/com/project/Tamago/service/LongTypingService.java
  backend/src/main/java/com/project/Tamago/service/ShortTypingService.java
  backend/src/main/java/com/project/Tamago/service/TypingHistoryService.java
  backend/src/test/java/com/project/Tamago/controller/TypingHistoryControllerTest.java
  backend/src/test/java/com/project/Tamago/service/TypingHistoryServiceTest.java
  backend/src/test/java/com/project/Tamago/service/UserServiceTest.java
Labels: 🛩 기능 추가, 💻 Backend

#139 [#125] 메인화면 디자인 수정
  client/public/images/tiers/tier-zero.png
  client/src/components/home/Banner/index.tsx
  client/src/components/home/Footer/index.tsx
  client/src/components/home/Landing/index.tsx
  client/src/components/home/Menus/MenuCard/index.tsx
  client/src/components/home/Menus/index.tsx
  client/src/components/home/Stats/index.tsx
  client/src/components/home/Tiers/index.tsx
  client/src/constants/animations.ts
  client/src/icons/ScrollIndicator.tsx
  client/src/styles/Button.ts
Labels: 💻 Frontend, 🎨 UI

#145 [refactor] short 글에 CustomResponse 추가
  backend/src/main/java/com/project/Tamago/controller/TypingController.java
  backend/src/test/java/com/project/Tamago/controller/TypingControllerTest.java
  backend/src/test/java/com/project/Tamago/service/UserServiceTest.java
Labels: 💻 Backend, ♻️ 리팩토링

#150 [#104] 긴글 세부조회 구현
  backend/src/main/generated/com/project/Tamago/dto/mapper/DataMapperImpl.java
  backend/src/main/java/com/project/Tamago/constants/enums/Role.java
  backend/src/main/java/com/project/Tamago/controller/TypingController.java
  backend/src/main/java/com/project/Tamago/controller/UserController.java
  backend/src/main/java/com/project/Tamago/domain/PagePosition.java
  backend/src/main/java/com/project/Tamago/dto/PageContentDto.java
  backend/src/main/java/com/project/Tamago/dto/mapper/DataMapper.java
  backend/src/main/java/com/project/Tamago/dto/responseDto/LongTypingDetailResDto.java
  backend/src/main/java/com/project/Tamago/exception/exceptionHandler/ErrorCode.java
  backend/src/main/java/com/project/Tamago/repository/LongTypingRepository.java
  backend/src/main/java/com/project/Tamago/repository/PagePositionRepository.java
  backend/src/main/java/com/project/Tamago/repository/UserRepository.java
  backend/src/main/java/com/project/Tamago/security/jwt/handler/CustomAuthenticationEntryPointHandler.java
  backend/src/main/java/com/project/Tamago/service/LongTypingService.java
  backend/src/main/java/com/project/Tamago/service/UserService.java
  backend/src/test/java/com/project/Tamago/service/LongTypingServiceTest.java
  etc/dataMaker/sample_long_typing._data.sql
Labels: 🛩 기능 추가, 💻 Backend

#142 긴 글 타자연습 동작 구현
  client/jest.config.js
  client/next.config.js
  client/package.json
  client/src/components/header/index.tsx
  client/src/components/practice/long/Content/index.tsx
  client/src/components/practice/long/Layout/index.tsx
  client/src/components/practice/long/Typing/InfoBar/InfoBarItem.tsx
  client/src/components/practice/long/Typing/InfoBar/index.tsx
  client/src/components/practice/long/Typing/index.tsx
  client/src/components/practice/long/common/TypingChar.tsx
  client/src/components/practice/long/common/TypingLine.tsx
  client/src/components/practice/short/CurrentTyping/index.tsx
  client/src/components/practice/short/index.tsx
  client/src/components/practice/short/useStopWatch.ts
  client/src/pages/practice/index.tsx
  client/src/pages/practice/long/[typingId]/[pageNum].tsx
  client/src/pages/practice/long/index.tsx
  client/src/pages/practice/short.tsx
  client/src/styles/font.css
  client/src/types/typing.ts
  client/src/utils/char.ts
  client/src/utils/paths.ts
  client/src/utils/test/char.test.ts
  client/src/utils/test/typing.test.ts
  client/src/utils/typing.ts
  client/tsconfig.json
  client/yarn.lock
Labels: 🛩 기능 추가, 💻 Frontend, 🎨 UI

#154 로그인시 유효성 검증
  backend/src/main/java/com/project/Tamago/exception/exceptionHandler/ControllerAdvice.java
  backend/src/main/java/com/project/Tamago/exception/exceptionHandler/ErrorCode.java
Labels: 🔨 버그 해결

#143 [#107] 디자인 시스템 스토리북 제작
  client/.storybook/main.js
  client/.storybook/preview.js
  client/src/components/common/Alert/index.stories.tsx
  client/src/components/common/Alert/index.tsx
  client/src/components/common/Checkbox/index.stories.tsx
  client/src/components/common/FormOr/index.stories.tsx
  client/src/components/common/FormOr/index.tsx
  client/src/components/common/RegexInput/index.stories.tsx
  client/src/components/footer/index.stories.tsx
  client/src/components/login/Form/index.stories.tsx
  client/src/components/password/index/index.tsx
  client/src/components/signup/Form/EmailInput/index.stories.tsx
  client/src/components/signup/Form/EmailInput/index.tsx
  client/src/components/signup/Form/index.tsx
  client/src/pages/designSystem.tsx
  client/src/stories/buttons.stories.tsx
  client/src/stories/inputs.stories.tsx
  client/src/styles/buttons.ts
  client/src/styles/inputs.ts
  client/src/styles/theme.ts
Labels: 💻 Frontend, 🎨 UI

#153 fix: 메인 화면 레이아웃 수정
  client/public/images/home/main-image.png
  client/src/components/home/Landing/index.tsx
  client/src/components/home/Menus/MenuCard/index.tsx
  client/src/components/home/Menus/index.tsx
  client/src/components/home/Stats/index.tsx
Labels: 💻 Frontend, 🎨 UI

#149 짧은 글 기능 구현
  client/src/apis/typing.ts
  client/src/components/practice/short/CorrectWriting/index.tsx
  client/src/components/practice/short/CurrentTyping/index.tsx
  client/src/components/practice/short/InfoBar/InfoBarItem.tsx
  client/src/components/practice/short/InfoBar/index.tsx
  client/src/components/practice/short/PrevTyping/index.tsx
  client/src/components/practice/short/index.tsx
  client/src/components/practice/short/shortTypingContext.tsx
  client/src/components/practice/short/useStopWatch.ts
  client/src/pages/practice/short.tsx
  client/src/utils/checkErrorWord.ts
  client/src/utils/typing.ts
Labels: 🛩 기능 추가, 💻 Frontend

#159 [#137] feat: 리드미 초안 작성
  README.md
Labels: 📝 문서 작업

#160 [#126] 선 차트, 막대 차트 제작
  client/package.json
  client/src/components/charts/BarChart/index.tsx
  client/src/components/charts/LineChart/index.tsx
  client/src/types/chart.ts
  client/yarn.lock
Labels: 🛩 기능 추가, 💻 Frontend

#177 speed up CI pipeline
  .github/workflows/frontend-ci.yml
Labels: 🌈 프로젝트 세팅, 💻 Frontend

#166 [#165] typing 로직 분리
  client/src/components/practice/long/Typing/index.tsx
  client/src/components/practice/short/currentTypingContext.tsx
  client/src/components/practice/short/index.tsx
  client/src/components/practice/short/shortTypingContext.tsx
  client/src/components/practice/short/useStopWatch.ts
Labels: 💻 Frontend, ♻️ 리팩토링

#173 회원가입 유효성 검증(이메일, 패스워드) 로직 추가
  backend/src/main/java/com/project/Tamago/dto/requestDto/JoinReqDto.java
  backend/src/test/java/com/project/Tamago/controller/AuthControllerTest.java
Labels: 💻 Backend, 🔨 버그 해결, ♻️ 리팩토링

#182 [#178] originalTyping, userTyping으로 네이밍 변경
  client/src/apis/typing.ts
  client/src/components/practice/short/CurrentTyping/index.tsx
  client/src/components/practice/short/OriginalTyping/index.tsx
  client/src/components/practice/short/PrevTyping/index.tsx
  client/src/components/practice/short/currentTypingContext.tsx
  client/src/components/practice/short/index.tsx
  client/src/components/practice/short/shortTypingContext.tsx
  client/src/components/practice/short/utils.ts
  client/src/pages/practice/short.tsx
Labels: 💻 Frontend, ♻️ 리팩토링

#167 긴 글 api 연결 및 임시 페이지 이동
  client/src/apis/typing.ts
  client/src/components/practice/long/Content/index.tsx
  client/src/components/practice/long/List/index.tsx
  client/src/components/practice/long/Typing/index.tsx
  client/src/components/practice/long/common/TypingChar.tsx
  client/src/components/practice/long/utils.ts
  client/src/components/practice/short/currentTypingContext.tsx
  client/src/pages/practice/long/[typingId]/[pageNum].tsx
  client/src/pages/practice/long/index.tsx
  client/src/types/typing.ts
  client/src/utils/test/typing.test.ts
  client/src/utils/typing.ts
Labels: 🛩 기능 추가, 💻 Frontend, 🎨 UI

#183 [#171,#172] 짧은 글 typing count 로직 변경
  client/src/components/practice/long/Typing/index.tsx
  client/src/components/practice/short/CurrentTyping/index.tsx
  client/src/components/practice/short/InfoBar/GrassEllipse.tsx
  client/src/components/practice/short/InfoBar/index.tsx
  client/src/components/practice/short/PrevTyping/index.tsx
  client/src/components/practice/short/_hook/contextShortTyping.tsx
  client/src/components/practice/short/_hook/useCurrentTyping.ts
  client/src/components/practice/short/_hook/useStopWatch.ts
  client/src/components/practice/short/index.tsx
  client/src/components/practice/short/utils.ts
  client/src/pages/practice/short.tsx
  client/src/utils/test/typing.test.ts
  client/src/utils/typing.ts
Labels: 💻 Frontend, 🔨 버그 해결, ♻️ 리팩토링

#188 for문 반복문을 고차함수로 리팩토링
  client/src/utils/test/typing.test.ts
  client/src/utils/typing.ts
Labels: 💻 Frontend, ♻️ 리팩토링

#186 긴 글 타이핑 상태 수정 및 ssr -> csr로 수정
  client/next.config.js
  client/src/components/practice/long/Content/index.tsx
  client/src/components/practice/long/List/index.tsx
  client/src/components/practice/long/Typing/InfoBar/index.tsx
  client/src/components/practice/long/Typing/index.tsx
  client/src/components/practice/long/TypingChar/index.tsx
  client/src/components/practice/long/TypingLine/index.tsx
  client/src/components/practice/long/common/TypingChar.tsx
  client/src/components/practice/long/common/TypingLine.tsx
  client/src/components/practice/long/utils.ts
  client/src/components/signup/Form/EmailInput/index.stories.tsx
  client/src/components/signup/Form/index.tsx
  client/src/components/signup/Terms/index.tsx
  client/src/pages/practice/long/[typingId]/[pageNum].tsx
  client/src/pages/practice/long/detail/index.tsx
  client/src/pages/practice/long/index.tsx
  client/src/types/typing.ts
  client/src/utils/paths.ts
  client/src/utils/typing.ts
Labels: 💻 Frontend, ♻️ 리팩토링

#187 [#176] 긴 글 상세페이지 이동, 긴 글 리스트로 나가기
  client/.storybook/main.js
  client/.storybook/preview.js
  client/package.json
  client/src/components/practice/long/Content/index.tsx
  client/src/components/practice/long/Typing/TypingHeader/index.stories.tsx
  client/src/components/practice/long/Typing/TypingHeader/index.tsx
  client/src/components/practice/long/Typing/index.tsx
  client/src/components/practice/long/TypingExit/index.stories.tsx
  client/src/components/practice/long/TypingExit/index.tsx
  client/src/components/practice/long/TypingPagination/index.stories.tsx
  client/src/components/practice/long/TypingPagination/index.tsx
  client/src/icons/Exit.tsx
  client/yarn.lock
Labels: 🛩 기능 추가, 💻 Frontend, 🎨 UI

#202 d2 coding 배포시 콘솔 오류
  client/src/styles/font.css
Labels: 💻 Frontend, 🔨 버그 해결

#203 font import 주소 변경
  client/src/styles/font.css
Labels: 💻 Frontend, 🔨 버그 해결

#206 [#136] 날짜별 속도, 정확도 통계 조회 API
  backend/src/main/java/com/project/Tamago/controller/StatisticController.java
  backend/src/main/java/com/project/Tamago/repository/TypingHistoryRepository.java
  backend/src/main/java/com/project/Tamago/service/StatisticService.java
  backend/src/main/java/com/project/Tamago/util/TypingHistoryGenerator.java
  backend/src/test/java/com/project/Tamago/service/StatisticServiceTest.java
  etc/mysql-query/tamago_ddl.sql
Labels: 💻 Backend

#210 깃허브 액션 잘못된 문법, api 요청 주소 수정
  .github/workflows/frontend-deploy.yml
  client/src/apis/typing.ts
Labels: 💻 Frontend, 🔨 버그 해결

#209 [#190] oauth kakao 로그인 구현 완료.
  backend/.gitignore
  backend/build.gradle
  backend/src/main/generated/com/project/Tamago/dto/mapper/DataMapperImpl.java
  backend/src/main/java/com/project/Tamago/config/SecurityConfig.java
  backend/src/main/java/com/project/Tamago/controller/AuthController.java
  backend/src/main/java/com/project/Tamago/controller/StatisticController.java
  backend/src/main/java/com/project/Tamago/dto/mapper/DataMapper.java
  backend/src/main/java/com/project/Tamago/dto/requestDto/LoginReqDto.java
  backend/src/main/java/com/project/Tamago/repository/TypingHistoryRepository.java
  backend/src/main/java/com/project/Tamago/security/CustomOAuth2User.java
  backend/src/main/java/com/project/Tamago/security/GoogleOAuth2User.java
  backend/src/main/java/com/project/Tamago/security/KakaoOAuth2User.java
  backend/src/main/java/com/project/Tamago/security/oauth2/CustomOAuth2UserService.java
  backend/src/main/java/com/project/Tamago/security/oauth2/OAuth2AuthenticationSuccessHandler.java
  backend/src/main/java/com/project/Tamago/security/oauth2/OAuthAttributes.java
  etc/mysql-query/tamago_ddl.sql
Labels: 🛩 기능 추가, 💻 Backend, ♻️ 리팩토링

#196 [#193] 헤더에 세부 메뉴들을 추가했습니다.
  client/src/components/footer/index.stories.tsx
  client/src/components/footer/index.tsx
  client/src/components/header/DropDown/index.tsx
  client/src/components/header/index.tsx
  client/src/components/login/Form/index.tsx
  client/src/components/login/index.tsx
  client/src/components/practice/long/List/index.tsx
  client/src/components/practice/long/Typing/index.tsx
  client/src/components/practice/long/TypingExit/index.tsx
  client/src/components/practice/long/TypingPagination/index.tsx
  client/src/components/signup/Complete/index.tsx
  client/src/components/signup/Form/index.tsx
  client/src/components/signup/Terms/index.tsx
  client/src/constants/paths.ts
  client/src/pages/_app.tsx
  client/src/pages/practice/index.tsx
  client/src/styles/buttons.ts
Labels: 🛩 기능 추가, 💻 Frontend, 🎨 UI

#204 [#195] 회원가입 로직 수정
  client/src/apis/auth.ts
  client/src/apis/index.ts
  client/src/components/login/Form/index.tsx
  client/src/components/signup/Form/index.tsx
  client/src/components/signup/Terms/IconCheckbox.tsx
  client/src/components/signup/Terms/index.tsx
  client/src/constants/responseCode.ts
  client/src/icons/GithubLogo.tsx
  client/src/icons/GoogleLogo.tsx
  client/src/types/apiResponse.ts
Labels: 🛩 기능 추가, 💻 Frontend

#214 api interceptor 수정 및 arrow function으로 변경
  client/src/apis/auth.ts
  client/src/apis/index.ts
Labels: 💻 Frontend, ♻️ 리팩토링

#215 [#195] 로그인 기능이 복구됐습니다.
  client/src/apis/auth.ts
  client/src/apis/index.ts
  client/src/components/header/index.tsx
  client/src/components/login/index.tsx
  client/src/components/signup/Form/index.tsx
Labels: 💻 Frontend, 🔨 버그 해결

#211 긴글 등록 및 목록 페이징
  backend/.gitignore
  backend/src/main/generated/com/project/Tamago/dto/mapper/DataMapperImpl.java
  backend/src/main/java/com/project/Tamago/config/SecurityConfig.java
  backend/src/main/java/com/project/Tamago/constants/enums/Language.java
  backend/src/main/java/com/project/Tamago/controller/TypingController.java
  backend/src/main/java/com/project/Tamago/domain/Bookmark.java
  backend/src/main/java/com/project/Tamago/domain/LongTyping.java
  backend/src/main/java/com/project/Tamago/domain/PagePosition.java
  backend/src/main/java/com/project/Tamago/domain/Register.java
  backend/src/main/java/com/project/Tamago/dto/mapper/DataMapper.java
  backend/src/main/java/com/project/Tamago/dto/requestDto/LongTypingReqDto.java
  backend/src/main/java/com/project/Tamago/repository/RegisterRepository.java
  backend/src/main/java/com/project/Tamago/service/LongTypingService.java
  backend/src/test/java/com/project/Tamago/service/LongTypingServiceTest.java
Labels: 🛩 기능 추가, 💻 Backend

#216 기존 constants폴더에 파일들과 errorcode, 성공응답코드들을 common으로 리팩토링
  backend/.gitignore
  backend/src/main/java/com/project/Tamago/common/Constant.java
  backend/src/main/java/com/project/Tamago/common/Response/CustomResponse.java
  backend/src/main/java/com/project/Tamago/common/converter/RoleConverter.java
  backend/src/main/java/com/project/Tamago/common/enums/KeyType.java
  backend/src/main/java/com/project/Tamago/common/enums/Language.java
  backend/src/main/java/com/project/Tamago/common/enums/Mode.java
  backend/src/main/java/com/project/Tamago/common/enums/ResponseCode.java
  backend/src/main/java/com/project/Tamago/common/enums/Role.java
  backend/src/main/java/com/project/Tamago/common/exception/CustomException.java
  backend/src/main/java/com/project/Tamago/common/exception/InvalidParameterException.java
  backend/src/main/java/com/project/Tamago/common/exception/exceptionHandler/ControllerAdvice.java
  backend/src/main/java/com/project/Tamago/common/exception/exceptionHandler/ErrorMessage.java
  backend/src/main/java/com/project/Tamago/config/SwaggerConfig.java
  backend/src/main/java/com/project/Tamago/constants/enums/Mode.java
  backend/src/main/java/com/project/Tamago/controller/AuthController.java
  backend/src/main/java/com/project/Tamago/controller/StatisticController.java
  backend/src/main/java/com/project/Tamago/controller/TypingController.java
  backend/src/main/java/com/project/Tamago/controller/TypingHistoryController.java
  backend/src/main/java/com/project/Tamago/controller/UserController.java
  backend/src/main/java/com/project/Tamago/domain/LongTyping.java
  backend/src/main/java/com/project/Tamago/domain/TypingHistory.java
  backend/src/main/java/com/project/Tamago/domain/User.java
  backend/src/main/java/com/project/Tamago/dto/WrongKey.java
  backend/src/main/java/com/project/Tamago/dto/mapper/DataMapper.java
  backend/src/main/java/com/project/Tamago/dto/requestDto/JoinReqDto.java
  backend/src/main/java/com/project/Tamago/exception/CustomException.java
  backend/src/main/java/com/project/Tamago/security/jwt/JwtAuthorizationFilter.java
  backend/src/main/java/com/project/Tamago/security/jwt/JwtTokenProvider.java
  backend/src/main/java/com/project/Tamago/security/jwt/handler/CustomAccessDeniedHandler.java
  backend/src/main/java/com/project/Tamago/security/jwt/handler/CustomAuthenticationEntryPointHandler.java
  backend/src/main/java/com/project/Tamago/security/oauth2/OAuth2AuthenticationSuccessHandler.java
  backend/src/main/java/com/project/Tamago/security/oauth2/OAuthAttributes.java
  backend/src/main/java/com/project/Tamago/service/AuthService.java
  backend/src/main/java/com/project/Tamago/service/LongTypingService.java
  backend/src/main/java/com/project/Tamago/service/PrincipalDetailService.java
  backend/src/main/java/com/project/Tamago/service/TypingHistoryService.java
  backend/src/main/java/com/project/Tamago/service/UserService.java
  backend/src/main/java/com/project/Tamago/util/TypingHistoryGenerator.java
  backend/src/test/java/com/project/Tamago/controller/AuthControllerTest.java
  backend/src/test/java/com/project/Tamago/controller/TypingControllerTest.java
  backend/src/test/java/com/project/Tamago/controller/TypingHistoryControllerTest.java
  backend/src/test/java/com/project/Tamago/jwt/JwtAuthorizationFilterTest.java
  backend/src/test/java/com/project/Tamago/service/AuthServiceTest.java
  backend/src/test/java/com/project/Tamago/service/LongTypingServiceTest.java
  backend/src/test/java/com/project/Tamago/service/TypingHistoryServiceTest.java
Labels: 💻 Backend, ♻️ 리팩토링

#219 유저정보를 가져오는 부분 argumentResolver로 리팩토링
  backend/src/main/java/com/project/Tamago/common/annotation/Login.java
  backend/src/main/java/com/project/Tamago/config/LoginArgumentResolver.java
  backend/src/main/java/com/project/Tamago/config/ResolverConfig.java
  backend/src/main/java/com/project/Tamago/config/SecurityConfig.java
  backend/src/main/java/com/project/Tamago/controller/StatisticController.java
  backend/src/main/java/com/project/Tamago/controller/TypingController.java
  backend/src/main/java/com/project/Tamago/controller/TypingHistoryController.java
  backend/src/main/java/com/project/Tamago/controller/UserController.java
  backend/src/main/java/com/project/Tamago/dto/LoginDto.java
  backend/src/main/java/com/project/Tamago/dto/mapper/DataMapper.java
  backend/src/main/java/com/project/Tamago/service/LongTypingService.java
  backend/src/main/java/com/project/Tamago/service/StatisticService.java
  backend/src/main/java/com/project/Tamago/service/TypingHistoryService.java
  backend/src/main/java/com/project/Tamago/service/UserService.java
  backend/src/test/java/com/project/Tamago/controller/TypingHistoryControllerTest.java
  backend/src/test/java/com/project/Tamago/controller/UserControllerTest.java
  backend/src/test/java/com/project/Tamago/service/LongTypingServiceTest.java
  backend/src/test/java/com/project/Tamago/service/StatisticServiceTest.java
  backend/src/test/java/com/project/Tamago/service/TypingHistoryServiceTest.java
  backend/src/test/java/com/project/Tamago/service/UserServiceTest.java
Labels: 🛩 기능 추가, 💻 Backend, ♻️ 리팩토링

#220 로그인시 유저 정보(닉네임) 반환
  backend/src/main/java/com/project/Tamago/config/LoginArgumentResolver.java
  backend/src/main/java/com/project/Tamago/controller/AuthController.java
  backend/src/main/java/com/project/Tamago/controller/StatisticController.java
  backend/src/main/java/com/project/Tamago/controller/TypingController.java
  backend/src/main/java/com/project/Tamago/controller/TypingHistoryController.java
  backend/src/main/java/com/project/Tamago/controller/UserController.java
  backend/src/main/java/com/project/Tamago/dto/Login.java
  backend/src/main/java/com/project/Tamago/dto/LoginDto.java
  backend/src/main/java/com/project/Tamago/dto/mapper/DataMapper.java
  backend/src/main/java/com/project/Tamago/dto/responseDto/LoginAutoResDto.java
  backend/src/main/java/com/project/Tamago/dto/responseDto/LoginResDto.java
  backend/src/main/java/com/project/Tamago/service/AuthService.java
  backend/src/test/java/com/project/Tamago/controller/AuthControllerTest.java
Labels: 🛩 기능 추가, 💻 Backend, ♻️ 리팩토링

#213 [#212] 로그인(인증) 이후 인가 작업
  client/package.json
  client/src/apis/auth.ts
  client/src/apis/index.ts
  client/src/atom/userProfile.ts
  client/src/components/header/index.tsx
  client/src/components/login/index.tsx
  client/src/hooks/useUserProfile.ts
  client/src/pages/_app.tsx
  client/src/pages/index.tsx
  client/src/types/apiResponse.ts
  client/src/types/user.ts
  client/yarn.lock
Labels: 🛩 기능 추가, 💻 Frontend

#217 [#207]짧은글 나가기 기능 + 결과 모달 구현
  client/src/components/common/Confirm/index.tsx
  client/src/components/common/IconButton/index.tsx
  client/src/components/common/ResultModal/InfoList/Item.tsx
  client/src/components/common/ResultModal/InfoList/index.tsx
  client/src/components/common/ResultModal/exam-mode.tsx
  client/src/components/common/ResultModal/practice-mode.tsx
  client/src/components/common/ResultModal/types.ts
  client/src/components/practice/long/Typing/index.tsx
  client/src/components/practice/short/InfoBar/ModeList.tsx
  client/src/components/practice/short/InfoBar/index.tsx
  client/src/components/practice/short/_hook/contextShortTyping.tsx
  client/src/components/practice/short/_hook/useCurrentTyping.ts
  client/src/components/practice/short/index.tsx
  client/src/hooks/useStopWatch.ts
  client/src/icons/Share.tsx
  client/src/styles/buttons.ts
  client/src/styles/colors.ts
  client/src/styles/modal.ts
  client/src/styles/theme.ts
Labels: 💻 Frontend, 🎨 UI

#233 [bugfix] swagger에서 cors에러가 생기는 문제 해결
  backend/src/main/java/com/project/Tamago/config/CorsConfig.java
Labels: 💻 Backend, 🔨 버그 해결

#222 짧은글 타이핑 게임
  client/.eslintrc.json
  client/src/apis/auth.ts
  client/src/apis/index.ts
  client/src/apis/typing.ts
  client/src/components/common/Confirm/index.tsx
  client/src/components/common/ResultModal/practice-mode.tsx
  client/src/components/practice/short/CurrentTyping/index.tsx
  client/src/components/practice/short/InfoBar/index.tsx
  client/src/components/practice/short/OriginalTyping/index.tsx
  client/src/components/practice/short/_hook/contextShortTyping.tsx
  client/src/components/practice/short/_hook/useCurrentTyping.ts
  client/src/components/practice/short/index.tsx
  client/src/hooks/useToggle.ts
  client/src/types/typing.ts
  client/src/utils/typing.ts
Labels: 💻 Frontend, 🔨 버그 해결

#224 404 페이지 완료
  client/public/images/page-404.png
  client/src/components/common/AuthLayout/index.tsx
  client/src/pages/404.tsx
  client/src/pages/_app.tsx
  client/src/pages/index.tsx
Labels: 💻 Frontend, 🎨 UI

#234 [#230] counting up hook
  client/src/hooks/useCountUp.ts
Labels: 🛩 기능 추가, 💻 Frontend
