Repository msdio/Tamago, pull requests merged in 2023-02, with the labels that each got.

#11 깃허브 템플릿 생성
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/pull_request_template.md
  client/.eslintignore
  client/.prettierignore
Labels: 🌈 프로젝트 세팅, 📝 문서 작업

#9 프론트엔드 프로젝트 세팅
  client/.storybook/main.js
  client/.storybook/preview.js
  client/package.json
  client/src/pages/_app.tsx
  client/src/pages/index.tsx
  client/tsconfig.json
  client/yarn.lock
Labels: 🌈 프로젝트 세팅, 💻 Frontend

#20 [#17] 인증 구현에 한 부분인 jwtTokenProvider 구현
  backend/build.gradle
  backend/src/main/java/com/project/Tamago/config/CorsConfig.java
  backend/src/main/java/com/project/Tamago/config/SecurityConfig.java
  backend/src/main/java/com/project/Tamago/config/SwaggerConfig.java
  backend/src/main/java/com/project/Tamago/controller/TestController.java
  backend/src/main/java/com/project/Tamago/domain/BaseTimeEntity.java
  backend/src/main/java/com/project/Tamago/domain/Bookmark.java
  backend/src/main/java/com/project/Tamago/domain/Contact.java
  backend/src/main/java/com/project/Tamago/domain/Register.java
  backend/src/main/java/com/project/Tamago/domain/Role.java
  backend/src/main/java/com/project/Tamago/domain/Typing.java
  backend/src/main/java/com/project/Tamago/domain/TypingHistory.java
  backend/src/main/java/com/project/Tamago/domain/User.java
  backend/src/main/java/com/project/Tamago/exception/CustomException.java
  backend/src/main/java/com/project/Tamago/exception/exceptionHandler/ControllerAdvice.java
  backend/src/main/java/com/project/Tamago/exception/exceptionHandler/ErrorCode.java
  backend/src/main/java/com/project/Tamago/exception/exceptionHandler/ErrorMessage.java
  backend/src/main/java/com/project/Tamago/jwt/JwtAuthorizationFilter.java
  backend/src/main/java/com/project/Tamago/jwt/JwtTokenProvider.java
  backend/src/main/java/com/project/Tamago/jwt/handler/CustomAccessDeniedHandler.java
  backend/src/main/java/com/project/Tamago/jwt/handler/CustomAuthenticationEntryPointHandler.java
  backend/src/main/java/com/project/Tamago/util/constant/KeyType.java
  backend/src/main/java/com/project/Tamago/util/constant/Role.java
  backend/src/main/java/com/project/Tamago/util/converter/RoleConverter.java
  backend/src/main/resources/application.yml
Labels: 🛩 기능 추가, 💻 Backend

#15 [#12] feat: login ui 구현
  client/component/login/guest.tsx
  client/component/login/layout.tsx
  client/component/login/login-form/index.tsx
  client/component/login/login-form/login-email-form.tsx
  client/component/login/login-form/password.tsx
  client/component/login/login-tab-panel-wrapper.tsx
  client/component/login/login-tab.tsx
  client/public/image/eyeslash.svg
  client/public/image/github-icon.svg
  client/public/image/google-icon.svg
  client/src/pages/_app.tsx
  client/src/pages/login.tsx
Labels: 🌈 프로젝트 세팅, 💻 Frontend, 🎨 UI

#27 [#25] ESLint, prettier, vscode 에디터 세팅
  .vscode/setting.json
  client/.eslintignore
  client/.eslintrc.json
  client/.prettierignore
  client/package.json
  client/src/pages/_app.tsx
  client/src/pages/index.tsx
  client/tsconfig.json
  client/yarn.lock
Labels: 🌈 프로젝트 세팅, 💻 Frontend

#23 [#14] 헤더, 푸터, 회원가입 페이지 UI 구현
  client/public/fonts/GangwonEduPower.tsx
  client/public/icons/right_arrow_1.svg
  client/public/images/eyeslash.svg
  client/public/images/github-icon.svg
  client/public/images/google-icon.svg
  client/src/components/common/InputForm.tsx
  client/src/components/common/SubmitButton.tsx
  client/src/components/footer/index.tsx
  client/src/components/header/index.tsx
  client/src/components/login/guest.tsx
  client/src/components/login/layout.tsx
  client/src/components/login/login-form/index.tsx
  client/src/components/login/login-form/login-email-form.tsx
  client/src/components/login/login-form/password.tsx
  client/src/components/login/login-tab-panel-wrapper.tsx
  client/src/components/login/login-tab.tsx
  client/src/components/signup/Form/index.tsx
  client/src/components/signup/Layout/index.tsx
  client/src/components/signup/Tos/index.tsx
  client/src/pages/_app.tsx
  client/src/pages/index.tsx
  client/src/pages/login.tsx
  client/src/pages/signup.tsx
  client/src/styles/theme.ts
Labels: 🛩 기능 추가, 💻 Frontend, 🎨 UI

#22 [#17] 인증, 인가 처리 fiter class 구현 및 security 적용
  backend/build.gradle
  backend/src/main/java/com/project/Tamago/config/RedisConfig.java
  backend/src/main/java/com/project/Tamago/config/SecurityConfig.java
  backend/src/main/java/com/project/Tamago/controller/TestController.java
  backend/src/main/java/com/project/Tamago/exception/exceptionHandler/ErrorCode.java
  backend/src/main/java/com/project/Tamago/jwt/JwtAuthorizationFilter.java
  backend/src/main/java/com/project/Tamago/jwt/JwtTokenProvider.java
  backend/src/main/java/com/project/Tamago/jwt/handler/CustomAccessDeniedHandler.java
  backend/src/main/java/com/project/Tamago/jwt/handler/CustomAuthenticationEntryPointHandler.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/project/Tamago/jwt/JwtAuthorizationFilterTest.java
Labels: 🛩 기능 추가, 💻 Backend

#33 [#30] design system setting
  .gitignore
  client/src/pages/_app.tsx
  client/src/pages/designSystem.tsx
  client/src/styles/Button.ts
  client/src/styles/theme.ts
Labels: 🌈 프로젝트 세팅, 💻 Frontend, 🎨 UI

#34 [#25] vscode 세팅 값 변경, eslint 적용 되도록 수정
  .vscode/setting.json
  .vscode/settings.json
  client/.eslintrc.json
  client/.prettierrc
  client/src/components/header/index.tsx
  client/tsconfig.json
Labels: 🌈 프로젝트 세팅, 💻 Frontend, 🔨 버그 해결

#38 [#25] 프론트 전체 파일 포맷팅
  client/src/components/common/InputForm.tsx
  client/src/components/common/SubmitButton.tsx
  client/src/components/header/index.tsx
  client/src/components/login/LoginForm/index.tsx
  client/src/components/login/LoginForm/login-email-form.tsx
  client/src/components/login/LoginForm/password.tsx
  client/src/components/login/guest.tsx
  client/src/components/login/layout.tsx
  client/src/components/login/login-tab-panel-wrapper.tsx
  client/src/components/signup/Form/index.tsx
  client/src/components/signup/Layout/index.tsx
  client/src/components/signup/Tos/index.tsx
  client/src/pages/_app.tsx
  client/src/pages/designSystem.tsx
  client/src/pages/login.tsx
  client/src/pages/signup.tsx
Labels: 🌈 프로젝트 세팅, 💻 Frontend

#39 [#32] 커스텀 체크박스를 구현했습니다.
  .gitignore
  .vscode/settings.json
  client/.storybook/main.js
  client/.storybook/preview.js
  client/package.json
  client/src/assets/icons/checkbox-check.svg
  client/src/components/common/Checkbox/index.stories.tsx
  client/src/components/common/Checkbox/index.tsx
  client/src/styles/theme.ts
  client/yarn.lock
Labels: 🛩 기능 추가, 💻 Frontend, 🎨 UI

#40 [#35] input 디자인 시스템 + 회원가입 ui 완성했습니다.
  client/src/assets/icons/right-arrow.svg
  client/src/components/common/Checkbox/index.tsx
  client/src/components/common/FormOr/index.tsx
  client/src/components/common/InputForm.tsx
  client/src/components/common/SubmitButton.tsx
  client/src/components/signup/Form/EmailButton.tsx
  client/src/components/signup/Form/RegexInput.tsx
  client/src/components/signup/Form/index.tsx
  client/src/components/signup/Layout/index.tsx
  client/src/components/signup/Terms/IconCheckbox.tsx
  client/src/components/signup/Terms/index.tsx
  client/src/components/signup/Tos/index.tsx
  client/src/icons/RightArrow.tsx
  client/src/pages/designSystem.tsx
  client/src/pages/signup.tsx
  client/src/styles/Button.ts
  client/src/styles/Input.ts
  client/src/styles/theme.ts
  client/src/utils/regex.ts
Labels: 🛩 기능 추가, 💻 Frontend, 🎨 UI

#54 [#26] 스토리북을 배포했습니다.
  client/build-storybook.log
  client/package.json
  client/src/styles/theme.ts
  client/yarn.lock
Labels: 💻 Frontend, 🎈 배포

#55 [#26] release: storybook 배포 자동화
  .github/workflows/chromatic.yml
Labels: 💻 Frontend, 🎈 배포

#56 [#26] release: storybook 배포 자동화 테스트
  client/package.json
Labels: 💻 Frontend, 🎈 배포

#52 [#31] docs: 기능 구현 템플릿 작성
  .github/ISSUE_TEMPLATE/new_feature.md
Labels: 📝 문서 작업

#62 [#17] 회원가입 & 일반 로그인 api 구현
  backend/src/main/java/com/project/Tamago/config/SecurityConfig.java
  backend/src/main/java/com/project/Tamago/controller/AuthController.java
  backend/src/main/java/com/project/Tamago/domain/PrincipalDetails.java
  backend/src/main/java/com/project/Tamago/domain/TypingHistory.java
  backend/src/main/java/com/project/Tamago/domain/User.java
  backend/src/main/java/com/project/Tamago/dto/JoinReqDto.java
  backend/src/main/java/com/project/Tamago/dto/LoginReqDto.java
  backend/src/main/java/com/project/Tamago/dto/SuccessResDto.java
  backend/src/main/java/com/project/Tamago/dto/TokenDto.java
  backend/src/main/java/com/project/Tamago/exception/CustomException.java
  backend/src/main/java/com/project/Tamago/exception/InvalidParameterException.java
  backend/src/main/java/com/project/Tamago/exception/exceptionHandler/ControllerAdvice.java
  backend/src/main/java/com/project/Tamago/exception/exceptionHandler/ErrorCode.java
  backend/src/main/java/com/project/Tamago/exception/exceptionHandler/ErrorMessage.java
  backend/src/main/java/com/project/Tamago/jwt/JwtTokenProvider.java
  backend/src/main/java/com/project/Tamago/repository/UserRepository.java
  backend/src/main/java/com/project/Tamago/service/AuthService.java
  backend/src/main/java/com/project/Tamago/service/PrincipalDetailService.java
  backend/src/main/java/com/project/Tamago/util/constants/Constant.java
  backend/src/main/java/com/project/Tamago/util/constants/KeyType.java
  backend/src/main/java/com/project/Tamago/util/constants/Role.java
  backend/src/main/java/com/project/Tamago/util/converter/RoleConverter.java
  backend/src/test/java/com/project/Tamago/TamagoApplicationTests.java
  backend/src/test/java/com/project/Tamago/controller/AuthControllerTest.java
  backend/src/test/java/com/project/Tamago/jwt/JwtTokenProviderTest.java
Labels: 🛩 기능 추가, 💻 Backend, 🔨 버그 해결

#64 [#28] 로그인 UI 수정
  client/src/components/common/FormOr/index.tsx
  client/src/components/common/RegexInput.tsx
  client/src/components/login/Form/index.tsx
  client/src/components/login/Layout/index.tsx
  client/src/components/login/LoginForm/index.tsx
  client/src/components/login/LoginForm/login-email-form.tsx
  client/src/components/login/LoginForm/password.tsx
  client/src/components/login/guest.tsx
  client/src/components/login/index.tsx
  client/src/components/login/layout.tsx
  client/src/components/login/login-tab-panel-wrapper.tsx
  client/src/components/login/login-tab.tsx
  client/src/components/signup/Form/index.tsx
  client/src/pages/designSystem.tsx
  client/src/pages/login.tsx
  client/src/styles/Typography.ts
  client/src/styles/colors.ts
  client/src/styles/styles.ts
  client/src/styles/theme.ts
Labels: 💻 Frontend, 🎨 UI, ♻️ 리팩토링

#70 [refactor] exception handler에서 오류 발생 시 log를 통해 메시지를 뱉도록 변경
  backend/src/main/java/com/project/Tamago/exception/exceptionHandler/ControllerAdvice.java
  dockerfile/backend/application-secret.yml
Labels: 💻 Backend, ♻️ 리팩토링

#63 [#26] footer, loginform, signup form 의 스토리를 추가했습니다.
  client/build-storybook.log
  client/src/components/footer/index.stories.tsx
  client/src/components/login/LoginForm/index.stories.tsx
  client/src/components/signup/Form/index.stories.tsx
  client/src/components/signup/Form/index.tsx
Labels: 💻 Frontend, 🎈 배포

#73 [#71] 회원가입 완료 페이지, 회원가입 상태 관리 수정
  client/.storybook/main.js
  client/public/fonts/GangwonEduPower.tsx
  client/public/images/signup-ok.png
  client/src/components/common/AuthLayout/index.tsx
  client/src/components/common/Checkbox/index.stories.tsx
  client/src/components/common/Checkbox/index.tsx
  client/src/components/common/FormOr/index.stories.tsx
  client/src/components/common/RegexInput/index.stories.tsx
  client/src/components/common/RegexInput/index.tsx
  client/src/components/header/index.tsx
  client/src/components/login/Form/index.tsx
  client/src/components/signup/Form/EmailInput.stories.tsx
  client/src/components/signup/Form/EmailInput.tsx
  client/src/components/signup/Form/index.tsx
  client/src/components/signup/Success/index.tsx
  client/src/components/signup/Terms/index.tsx
  client/src/hooks/useRegexInputs.ts
  client/src/pages/designSystem.tsx
  client/src/pages/signup.tsx
  client/src/pages/signup/form.tsx
  client/src/pages/signup/success.tsx
  client/src/pages/signup/terms.tsx
  client/src/styles/Button.ts
  client/src/styles/Input.ts
  client/src/styles/colors.ts
Labels: 💻 Frontend, 🎨 UI, ♻️ 리팩토링

#76 [#68] backend deploy pipeline을 튼튼하게 변경
  .github/workflows/backend-deploy.yml
  dockerfile/backend/backend_install.sh
  dockerfile/backend/delete_not_use_image_file.sh
Labels: 💻 Backend, 🔨 버그 해결, 🎈 배포, ♻️ 리팩토링

#77 [refactor] 쓰지않는 파라미터값 제거
  backend/src/main/java/com/project/Tamago/controller/AuthController.java
Labels: 💻 Backend, ♻️ 리팩토링

#81 [#80] Front API 초기 세팅
  client/package.json
  client/src/apis/auth.ts
  client/src/apis/index.ts
  client/yarn.lock
Labels: 🌈 프로젝트 세팅, 💻 Frontend

#85 [#79] feat : local backend docker image build
  .github/workflows/backend-deploy-local.yml
  dockerfile/backend-run.sh
  dockerfile/backend/Dockerfile-Local
Labels: 💻 Backend, 🎈 배포

#74 [#13] 메인 페이지 퍼블리싱
  client/.storybook/preview.js
  client/public/icons/tamago-logo.svg
  client/public/images/eyeslash.svg
  client/public/images/github-icon.svg
  client/public/images/google-icon.svg
  client/public/images/home/background.png
  client/public/images/home/main-image.png
  client/public/images/home/white-chicken.png
  client/public/images/home/yellow-chick.png
  client/public/images/tamago-logo.png
  client/src/assets/icons/checkbox-check.svg
  client/src/assets/icons/right-arrow.svg
  client/src/components/footer/index.tsx
  client/src/components/header/index.tsx
  client/src/components/home/Landing/index.tsx
  client/src/components/home/Layout/index.tsx
  client/src/components/login/Form/index.tsx
  client/src/components/signup/Form/index.tsx
  client/src/icons/TamagoLogo.tsx
  client/src/pages/_app.tsx
  client/src/pages/index.tsx
  client/src/styles/styles.ts
  client/tsconfig.json
Labels: 💻 Frontend, 🎨 UI

#95 [#88] 스토리북 배포 자동화 with github actions
  .github/workflows/chromatic.yml
  client/.storybook/main.js
  client/src/components/login/LoginForm/index.stories.tsx
  client/src/components/login/LoginForm/index.tsx
  client/src/utils/paths.ts
Labels: 💻 Frontend, 🎈 배포

#84 [#66] user profile API 구현
  backend/src/main/java/com/project/Tamago/config/SecurityConfig.java
  backend/src/main/java/com/project/Tamago/controller/AuthController.java
  backend/src/main/java/com/project/Tamago/controller/UserController.java
  backend/src/main/java/com/project/Tamago/domain/User.java
  backend/src/main/java/com/project/Tamago/dto/SuccessMessage.java
  backend/src/main/java/com/project/Tamago/dto/requestDto/JoinReqDto.java
  backend/src/main/java/com/project/Tamago/dto/requestDto/LoginReqDto.java
  backend/src/main/java/com/project/Tamago/dto/requestDto/ModifyProfileReqDto.java
  backend/src/main/java/com/project/Tamago/dto/responseDto/ProfileResDto.java
  backend/src/main/java/com/project/Tamago/exception/exceptionHandler/ControllerAdvice.java
  backend/src/main/java/com/project/Tamago/exception/exceptionHandler/ErrorCode.java
  backend/src/main/java/com/project/Tamago/mapper/UserMapper.java
  backend/src/main/java/com/project/Tamago/repository/UserRepository.java
  backend/src/main/java/com/project/Tamago/service/AuthService.java
  backend/src/main/java/com/project/Tamago/service/PrincipalDetailService.java
  backend/src/main/java/com/project/Tamago/service/UserService.java
  backend/src/main/java/com/project/Tamago/util/security/PrincipalDetails.java
  backend/src/test/java/com/project/Tamago/TamagoApplicationTests.java
  backend/src/test/java/com/project/Tamago/controller/AuthControllerTest.java
  backend/src/test/java/com/project/Tamago/controller/UserControllerTest.java
  backend/src/test/java/com/project/Tamago/jwt/JwtTokenProviderTest.java
  backend/src/test/java/com/project/Tamago/service/UserServiceTest.java
Labels: 🛩 기능 추가, 💻 Backend

#96 [#67] 프론트엔드 github actions 파이프라인 구축
  .github/workflows/frontend-ci.yml
  .github/workflows/frontend-deploy.yml
  client/package.json
  client/src/apis/auth.ts
  client/src/components/common/FormOr/index.stories.tsx
  client/src/components/footer/index.stories.tsx
  client/src/components/header/index.tsx
  client/src/components/login/Form/index.tsx
  client/src/components/signup/Form/index.tsx
  client/src/components/signup/Terms/IconCheckbox.tsx
  client/src/components/signup/Terms/index.tsx
  client/src/hooks/useRegexInputs.ts
  client/src/styles/Typography.ts
  client/src/utils/test/path.test.js
Labels: 🌈 프로젝트 세팅, 💻 Frontend, 🎈 배포

#78 회원가입 버튼 클릭시 입력창 포커싱
  client/src/apis/email.ts
  client/src/apis/user.ts
  client/src/components/common/Alert/index.tsx
  client/src/components/common/RegexInput/index.tsx
  client/src/components/header/index.tsx
  client/src/components/password/index/index.tsx
  client/src/components/signup/Complete/index.tsx
  client/src/components/signup/Form/EmailInput.tsx
  client/src/components/signup/Form/index.tsx
  client/src/components/signup/Terms/index.tsx
  client/src/pages/signup/complete.tsx
  client/src/utils/paths.ts
Labels: 🛩 기능 추가, 💻 Frontend, 🎨 UI

#83 [#82] 로그인 API
  client/src/apis/auth.ts
  client/src/apis/email.ts
  client/src/apis/user.ts
  client/src/components/login/Form/index.tsx
  client/src/components/login/index.tsx
  client/src/utils/paths.ts
Labels: 🛩 기능 추가, 💻 Frontend

#100 [document] backend-run.sh 사용법 readme에 추가
  dockerfile/backend-run-window.sh
  dockerfile/backend-run.sh
  dockerfile/readme.md
Labels: 📝 문서 작업

#99 [#37] 회원가입 api 연결
  client/src/apis/auth.ts
  client/src/apis/email.ts
  client/src/apis/error.ts
  client/src/apis/user.ts
  client/src/components/signup/Complete/index.tsx
  client/src/components/signup/Form/index.tsx
Labels: 🛩 기능 추가, 💻 Frontend

#98 [#17] Auth api 나머지 구현
  backend/src/main/java/com/project/Tamago/config/SwaggerConfig.java
  backend/src/main/java/com/project/Tamago/controller/AuthController.java
  backend/src/main/java/com/project/Tamago/controller/UserController.java
  backend/src/main/java/com/project/Tamago/dto/CustomResponse.java
  backend/src/main/java/com/project/Tamago/dto/requestDto/PasswordReqDto.java
  backend/src/main/java/com/project/Tamago/dto/responseDto/ProfileResDto.java
  backend/src/main/java/com/project/Tamago/exception/exceptionHandler/ErrorCode.java
  backend/src/main/java/com/project/Tamago/jwt/JwtAuthorizationFilter.java
  backend/src/main/java/com/project/Tamago/jwt/JwtTokenProvider.java
  backend/src/main/java/com/project/Tamago/service/AuthService.java
  backend/src/main/java/com/project/Tamago/service/UserService.java
  backend/src/main/java/com/project/Tamago/util/constants/Constant.java
  backend/src/main/java/com/project/Tamago/util/security/Token.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/project/Tamago/controller/AuthControllerTest.java
  backend/src/test/java/com/project/Tamago/jwt/JwtTokenProviderTest.java
  backend/src/test/java/com/project/Tamago/service/AuthServiceTest.java
  backend/src/test/java/com/project/Tamago/service/UserServiceTest.java
Labels: 🛩 기능 추가, 💻 Backend, ♻️ 리팩토링

#109 [refactor] change directory structure, make short typing Test code
  backend/src/main/java/com/project/Tamago/config/SecurityConfig.java
  backend/src/main/java/com/project/Tamago/config/SwaggerConfig.java
  backend/src/main/java/com/project/Tamago/constants/Constant.java
  backend/src/main/java/com/project/Tamago/constants/converter/RoleConverter.java
  backend/src/main/java/com/project/Tamago/constants/enums/KeyType.java
  backend/src/main/java/com/project/Tamago/constants/enums/Mode.java
  backend/src/main/java/com/project/Tamago/constants/enums/Role.java
  backend/src/main/java/com/project/Tamago/controller/AuthController.java
  backend/src/main/java/com/project/Tamago/domain/TypingHistory.java
  backend/src/main/java/com/project/Tamago/domain/User.java
  backend/src/main/java/com/project/Tamago/dto/ShortTypingDto.java
  backend/src/main/java/com/project/Tamago/dto/mapper/UserMapper.java
  backend/src/main/java/com/project/Tamago/dto/requestDto/JoinReqDto.java
  backend/src/main/java/com/project/Tamago/dto/responseDto/ShortTypingListResDto.java
  backend/src/main/java/com/project/Tamago/repository/TypingHistoryRepository.java
  backend/src/main/java/com/project/Tamago/repository/TypingRepository.java
  backend/src/main/java/com/project/Tamago/security/PrincipalDetails.java
  backend/src/main/java/com/project/Tamago/security/Token.java
  backend/src/main/java/com/project/Tamago/security/jwt/JwtAuthorizationFilter.java
  backend/src/main/java/com/project/Tamago/security/jwt/JwtTokenProvider.java
  backend/src/main/java/com/project/Tamago/security/jwt/handler/CustomAccessDeniedHandler.java
  backend/src/main/java/com/project/Tamago/security/jwt/handler/CustomAuthenticationEntryPointHandler.java
  backend/src/main/java/com/project/Tamago/service/AuthService.java
  backend/src/main/java/com/project/Tamago/service/PrincipalDetailService.java
  backend/src/main/java/com/project/Tamago/service/ShortTypingSerivce.java
  backend/src/main/java/com/project/Tamago/service/UserService.java
  backend/src/test/java/com/project/Tamago/controller/AuthControllerTest.java
  backend/src/test/java/com/project/Tamago/jwt/JwtAuthorizationFilterTest.java
  backend/src/test/java/com/project/Tamago/jwt/JwtTokenProviderTest.java
  backend/src/test/java/com/project/Tamago/service/ShortTypingServiceTest.java
  backend/src/test/java/com/project/Tamago/service/UserServiceTest.java
Labels: 💻 Backend, ♻️ 리팩토링
